### ISSUE TITLE
chef-vault recipe fails to install gem: chef_gem[chef-vault] (chef-vault::default line 21) had an error: NoMethodError: undefined method `full_name' for nil:NilClass

### ISSUE THREAD

**Issue by billclark91** [chef-cookbooks/chef-vault#18]
Chef-vault recipe failing to install chef-vault gem.  I'm running chef 11.12.4.  

Platform Info:
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise

Running chef-client with debug output correctly detect embedded location of ruby:

```
Recipe: chef-vault::default
  * chef_gem[chef-vault] action install[2014-11-04T21:04:39-07:00] INFO: Processing chef_gem[chef-vault] action install (chef-vault::default line 21)
[2014-11-04T21:04:39-07:00] DEBUG: chef_gem[chef-vault] detected omnibus installation in /opt/chef/embedded/bin
[2014-11-04T21:04:39-07:00] DEBUG: chef_gem[chef-vault] using gem from running ruby environment
[2014-11-04T21:04:39-07:00] DEBUG: chef_gem[chef-vault] no installed version found for chef-vault (~> 2.2)
```

Any assistance would be greatly appreciated.

Stack Trace as follows:

```
Starting Chef Client, version 11.12.4
resolving cookbooks for run list: ["apt", "java", "activemq", "c4_splunk::queue"]
Synchronizing Cookbooks:
  - chef-vault
  - chef-splunk
  - c4_splunk
  - java
  - activemq
  - apt
Compiling Cookbooks...
[2014-11-04T20:47:20-07:00] WARN: Cloning resource attributes for execute[apt-get-update] from prior resource (CHEF-3694)
[2014-11-04T20:47:20-07:00] WARN: Previous execute[apt-get-update]: /var/chef/cache/cookbooks/apt/recipes/default.rb:29:in `from_file'
[2014-11-04T20:47:20-07:00] WARN: Current  execute[apt-get-update]: /var/chef/cache/cookbooks/apt/recipes/default.rb:38:in `from_file'
Recipe: chef-vault::default
  * chef_gem[chef-vault] action install
================================================================================
Error executing action `install` on resource 'chef_gem[chef-vault]'
================================================================================

NoMethodError
-------------
undefined method `full_name' for nil:NilClass

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/chef-vault/recipes/default.rb:21:in `from_file'
/var/chef/cache/cookbooks/c4_splunk/recipes/client.rb:11:in `from_file'
/var/chef/cache/cookbooks/c4_splunk/recipes/queue.rb:13:in `from_file'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/chef-vault/recipes/default.rb

 21: chef_gem 'chef-vault' do
 22:   version node['chef-vault']['version']
 23: end
 24: 

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/chef-vault/recipes/default.rb:21:in `from_file'

chef_gem("chef-vault") do
  provider Chef::Provider::Package::Rubygems
  action :install
  retries 0
  retry_delay 2
  guard_interpreter :default
  package_name "chef-vault"
  version "~> 2.2"
  cookbook_name "chef-vault"
  recipe_name "default"
end

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/c4_splunk/recipes/queue.rb
================================================================================

NoMethodError
-------------
chef_gem[chef-vault] (chef-vault::default line 21) had an error: NoMethodError: undefined method `full_name' for nil:NilClass

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/chef-vault/recipes/default.rb:21:in `from_file'
  /var/chef/cache/cookbooks/c4_splunk/recipes/client.rb:11:in `from_file'
  /var/chef/cache/cookbooks/c4_splunk/recipes/queue.rb:13:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/chef-vault/recipes/default.rb:

 14:  #
 15:  # Unless required by applicable law or agreed to in writing, software
 16:  # distributed under the License is distributed on an "AS IS" BASIS,
 17:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 18:  # See the License for the specific language governing permissions and
 19:  # limitations under the License.
 20:  
 21>> chef_gem 'chef-vault' do
 22:    version node['chef-vault']['version']
 23:  end
 24:  
 25:  require 'chef-vault'
 26:  

Running handlers:
[2014-11-04T20:47:40-07:00] ERROR: Running exception handlers
Running handlers complete

[2014-11-04T20:47:40-07:00] ERROR: Exception handlers complete
[2014-11-04T20:47:40-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 23.612362801 seconds
[2014-11-04T20:47:40-07:00] ERROR: chef_gem[chef-vault] (chef-vault::default line 21) had an error: NoMethodError: undefined method `full_name' for nil:NilClass
[2014-11-04T20:47:40-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Top of debug stack trace (if it helps):
```[2014-11-04T21:05:09-07:00] DEBUG: Re-raising exception: NoMethodError - chef_gem[chef-vault] (chef-vault::default line 21) had an error: NoMethodError: undefined method`full_name' for nil:NilClass
/opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:136:in `block in gather_dependencies'
  /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:136:in`map'
  /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:136:in `gather_dependencies'
  /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:267:in`install'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider/package/rubygems.rb:201:in `block (2 levels) in install'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider/package/rubygems.rb:224:in`with_correct_verbosity'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider/package/rubygems.rb:200:in `block in install'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider/package/rubygems.rb:110:in`with_gem_sources'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider/package/rubygems.rb:199:in `install'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider/package/rubygems.rb:511:in`install_package'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider/package.rb:82:in `block in action_install'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/mixin/why_run.rb:52:in`call'

```
```

**Comment by mb250691** [comment]
> Issue is not with recipe, but with corporate DNS. Once issue was resolved with DNS, chef_gem[chef-vault] successfully installed.
> 
> Sorry for the false alarm.
@billclark91 

Can you elaborate  please?
