### ISSUE TITLE
Deprecated features used with Chef: 12.5.1

### ISSUE THREAD

**Issue by tiago-cruz-movile** [chef-cookbooks/chef-vault#43]
```
Deprecated features used!
  install_dir nil currently does not overwrite the value of install_dir. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :install_dir, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/cache/chef/cookbooks/redisio/recipes/install.rb:35:in `block in from_file'
  Using an LWRP provider by its name (Ark) directly is no longer supported in Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead. at 1 location:
    - /var/cache/chef/cookbooks/ark/resources/default.rb:26:in `initialize'
  chef_gem[chef-vault] chef_gem compile_time installation is deprecated at 1 location:
    - /var/cache/chef/cookbooks/mascherano/recipes/default.rb:10:in `from_file'
  chef_gem[chef-vault] Please set `compile_time false` on the resource to use the new behavior. at 1 location:
    - /var/cache/chef/cookbooks/mascherano/recipes/default.rb:10:in `from_file'
  chef_gem[chef-vault] or set `compile_time true` on the resource if compile_time behavior is required. at 1 location:
    - /var/cache/chef/cookbooks/mascherano/recipes/default.rb:10:in `from_file'
```

**Comment by DPD-30** [comment]
compile time true also caused problem when you need to use a private gem repo.  .gemrc file can't be writen at compile time so the gem install fails.  If gem is installed at converge as oposed to compile gemrc can be put in place first.  

What is the comiple time need for the gem?

**Comment by cheeseplus** [comment]
The gem has been moved to metadata.rb which eliminates the warnings which apply to this cookbook (a few of those don't).
